version: '3'
services:
  tag-my-outfit:
    image: sipgisr/tag-my-outfit:latest
    environment:
      HOST: "[::]"
      PORT: 50051
  processing-node:
    image: node:latest
    environment:
      SELF_PORT: 50050
      NEXT_HOST: host.docker.internal
      NEXT_PORT: 50052
      PROCESSING_HOST: tag-my-outfit
      PROCESSING_PORT: 50051
      PROCESSING_METHOD: predict
    ports:
      - 50050:50050
    depends_on:
      - tag-my-outfit
    command: bash -c "/usr/bin/wait-for-it.sh --timeout=0 tag-my-outfit:50051 && java -cp '*' pipeline.node.App"