version: '3'
services:
  tag-my-outfit:
    image: sipgisr/tag-my-outfit:latest
    environment:
      HOST: "[::]"
      PORT: 50051
  orchestrator-node:
    image: tag-my-outfit-orchestrator:latest
    depends_on:
      - tag-my-outfit
    command: bash -c "/usr/bin/wait-for-all.sh stages.csv && java -cp '*' pipeline.orchestrator.App"