version: '3'
services:
  tag-my-outfit:
    image: sipgisr/tag-my-outfit:latest
    environment:
      HOST: "[::]"
      PORT: 50051
  orchestrator-node:
    build: .
    image: tag-my-outfit-orchestrator:latest
    depends_on:
      - tag-my-outfit
    command: bash -c "/usr/bin/wait-for-all.sh urls.txt && java -cp '*' pipeline.orchestrator.App"
