version: '3'
services:
  # By default the gRPC servers are listening at port 50051
  # We can distinguish servers by host, defined by the service name
  # See https://docs.docker.com/compose/networking/
  image-source:
    build:
      context: ./Images Folder Source/
      dockerfile: docker/Dockerfile
    image: image-source:latest
    volumes:
    - type: bind
      source: ./images/
      target: /app/images/
  open-pose:
    image: open-pose-grpc-estimation:latest
  open-cv:
    image: opencv-grpc-server:latest
    volumes:
    - type: bind
      source: ./Crop/src/crop_function.py
      # Copy to external.py to use external as module name
      # which is the default
      target: /opencv-grpc/external.py
  tag-my-outfit:
    image: sipgisr/tag-my-outfit:latest
    environment:
      HOST: "[::]"
      PORT: 50051
  visualization:
    build:
      context: ./Visualization Destination/
      dockerfile: docker/Dockerfile
    image: visualization:latest
    # Only port visible outside the docker environment
    # to see the images in the web
    ports:
    - 5000:5000
  orchestrator-node:
    image: orchestrator:latest
    volumes: 
    - type: bind
      source: ./Config
      target: /app/config
    environment:
      CONFIG_FILE: "config/config.yaml"
    command: bash -c "/usr/bin/wait-for-all.sh config/urls.txt && java -cp '*' pipeline.orchestrator.App"
