# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visualization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pipeline.core.messages.grpc import image_pb2 as pipeline_dot_core_dot_messages_dot_grpc_dot_image__pb2
from outfit_tagging.interface import service_pb2 as outfit__tagging_dot_interface_dot_service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='visualization.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13visualization.proto\x1a\'pipeline/core/messages/grpc/image.proto\x1a&outfit_tagging/interface/service.proto\"X\n\x14VisualizationRequest\x12\x1a\n\nimage_data\x18\x01 \x01(\x0b\x32\x06.Image\x12$\n\nprediction\x18\x02 \x01(\x0b\x32\x10.PredictResponse\"\x17\n\x15VisualizationResponse2R\n\x14VisualizationService\x12:\n\tVisualize\x12\x15.VisualizationRequest\x1a\x16.VisualizationResponseb\x06proto3'
  ,
  dependencies=[pipeline_dot_core_dot_messages_dot_grpc_dot_image__pb2.DESCRIPTOR,outfit__tagging_dot_interface_dot_service__pb2.DESCRIPTOR,])




_VISUALIZATIONREQUEST = _descriptor.Descriptor(
  name='VisualizationRequest',
  full_name='VisualizationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='VisualizationRequest.image_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prediction', full_name='VisualizationRequest.prediction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=192,
)


_VISUALIZATIONRESPONSE = _descriptor.Descriptor(
  name='VisualizationResponse',
  full_name='VisualizationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=217,
)

_VISUALIZATIONREQUEST.fields_by_name['image_data'].message_type = pipeline_dot_core_dot_messages_dot_grpc_dot_image__pb2._IMAGE
_VISUALIZATIONREQUEST.fields_by_name['prediction'].message_type = outfit__tagging_dot_interface_dot_service__pb2._PREDICTRESPONSE
DESCRIPTOR.message_types_by_name['VisualizationRequest'] = _VISUALIZATIONREQUEST
DESCRIPTOR.message_types_by_name['VisualizationResponse'] = _VISUALIZATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisualizationRequest = _reflection.GeneratedProtocolMessageType('VisualizationRequest', (_message.Message,), {
  'DESCRIPTOR' : _VISUALIZATIONREQUEST,
  '__module__' : 'visualization_pb2'
  # @@protoc_insertion_point(class_scope:VisualizationRequest)
  })
_sym_db.RegisterMessage(VisualizationRequest)

VisualizationResponse = _reflection.GeneratedProtocolMessageType('VisualizationResponse', (_message.Message,), {
  'DESCRIPTOR' : _VISUALIZATIONRESPONSE,
  '__module__' : 'visualization_pb2'
  # @@protoc_insertion_point(class_scope:VisualizationResponse)
  })
_sym_db.RegisterMessage(VisualizationResponse)



_VISUALIZATIONSERVICE = _descriptor.ServiceDescriptor(
  name='VisualizationService',
  full_name='VisualizationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=219,
  serialized_end=301,
  methods=[
  _descriptor.MethodDescriptor(
    name='Visualize',
    full_name='VisualizationService.Visualize',
    index=0,
    containing_service=None,
    input_type=_VISUALIZATIONREQUEST,
    output_type=_VISUALIZATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VISUALIZATIONSERVICE)

DESCRIPTOR.services_by_name['VisualizationService'] = _VISUALIZATIONSERVICE

# @@protoc_insertion_point(module_scope)
