# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visualization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='visualization.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13visualization.proto\"l\n\x14VisualizationRequest\x12(\n\x0fpredict_request\x18\x01 \x01(\x0b\x32\x0f.PredictRequest\x12*\n\x10predict_response\x18\x02 \x01(\x0b\x32\x10.PredictResponse\"T\n\x0ePredictRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x16\n\x0e\x61ll_categories\x18\x02 \x01(\x08\x12\x16\n\x0e\x61ll_attributes\x18\x03 \x01(\x08\"[\n\x0fPredictResponse\x12#\n\ncategories\x18\x02 \x03(\x0b\x32\x0f.Correspondence\x12#\n\nattributes\x18\x03 \x03(\x0b\x32\x0f.Correspondence\".\n\x0e\x43orrespondence\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"\x07\n\x05\x45mpty2B\n\x14VisualizationService\x12*\n\tVisualize\x12\x15.VisualizationRequest\x1a\x06.Emptyb\x06proto3'
)




_VISUALIZATIONREQUEST = _descriptor.Descriptor(
  name='VisualizationRequest',
  full_name='VisualizationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predict_request', full_name='VisualizationRequest.predict_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predict_response', full_name='VisualizationRequest.predict_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=131,
)


_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='PredictRequest.image_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='all_categories', full_name='PredictRequest.all_categories', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='all_attributes', full_name='PredictRequest.all_attributes', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=217,
)


_PREDICTRESPONSE = _descriptor.Descriptor(
  name='PredictResponse',
  full_name='PredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='categories', full_name='PredictResponse.categories', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='PredictResponse.attributes', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=310,
)


_CORRESPONDENCE = _descriptor.Descriptor(
  name='Correspondence',
  full_name='Correspondence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='Correspondence.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Correspondence.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=358,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=367,
)

_VISUALIZATIONREQUEST.fields_by_name['predict_request'].message_type = _PREDICTREQUEST
_VISUALIZATIONREQUEST.fields_by_name['predict_response'].message_type = _PREDICTRESPONSE
_PREDICTRESPONSE.fields_by_name['categories'].message_type = _CORRESPONDENCE
_PREDICTRESPONSE.fields_by_name['attributes'].message_type = _CORRESPONDENCE
DESCRIPTOR.message_types_by_name['VisualizationRequest'] = _VISUALIZATIONREQUEST
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['PredictResponse'] = _PREDICTRESPONSE
DESCRIPTOR.message_types_by_name['Correspondence'] = _CORRESPONDENCE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisualizationRequest = _reflection.GeneratedProtocolMessageType('VisualizationRequest', (_message.Message,), {
  'DESCRIPTOR' : _VISUALIZATIONREQUEST,
  '__module__' : 'visualization_pb2'
  # @@protoc_insertion_point(class_scope:VisualizationRequest)
  })
_sym_db.RegisterMessage(VisualizationRequest)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTREQUEST,
  '__module__' : 'visualization_pb2'
  # @@protoc_insertion_point(class_scope:PredictRequest)
  })
_sym_db.RegisterMessage(PredictRequest)

PredictResponse = _reflection.GeneratedProtocolMessageType('PredictResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTRESPONSE,
  '__module__' : 'visualization_pb2'
  # @@protoc_insertion_point(class_scope:PredictResponse)
  })
_sym_db.RegisterMessage(PredictResponse)

Correspondence = _reflection.GeneratedProtocolMessageType('Correspondence', (_message.Message,), {
  'DESCRIPTOR' : _CORRESPONDENCE,
  '__module__' : 'visualization_pb2'
  # @@protoc_insertion_point(class_scope:Correspondence)
  })
_sym_db.RegisterMessage(Correspondence)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'visualization_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_VISUALIZATIONSERVICE = _descriptor.ServiceDescriptor(
  name='VisualizationService',
  full_name='VisualizationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=369,
  serialized_end=435,
  methods=[
  _descriptor.MethodDescriptor(
    name='Visualize',
    full_name='VisualizationService.Visualize',
    index=0,
    containing_service=None,
    input_type=_VISUALIZATIONREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VISUALIZATIONSERVICE)

DESCRIPTOR.services_by_name['VisualizationService'] = _VISUALIZATIONSERVICE

# @@protoc_insertion_point(module_scope)
